### ISSUE TITLE
Test data has only unrelated GEOMETRIOBJEKT

### ISSUE THREAD

**Issue by bjornharrtell** [Kortforsyningen/FIRE-DDL#33] opened 2018-12-10 09:22 UTC
It appears that in the test data the GEOMETRIOBJEKT are not related to any PUNKT that is referred to in any row of the OBSERVATION table. I.e I get 0 counts on the following queries:

```sql
SELECT COUNT(1)
FROM GEOMETRIOBJEKT G, OBSERVATION O
WHERE G.PUNKTID = O.SIGTEPUNKTID
-- 0

SELECT COUNT(1)
FROM GEOMETRIOBJEKT G, OBSERVATION O
WHERE G.PUNKTID = O.OPSTILLINGSPUNKTID
-- 0
```

Unless I'm misunderstanding something, I think I need to have some test data for these relations.

**Comment by kbevers** [comment] 2018-12-10 09:50
For those two queries I get 290613 and 291657 when I run it on the fully migrated database we have in-house. @nikolajkamstrup mentioned earlier today that something went wrong with the datadump of the geometries at some point. This may be caused by that problem. It may also be that the test data is poorly chosen. The next datadump will include data for a 1000 points which should increase the chances of a better test dataset.

**Comment by nikolajkamstrup** [comment] 2018-12-10 10:19
I made a data dump Monday last week but the geometries were not included. So I made a new datadump of the table GEOMETRIOBJEKT Thurdsay last week but I didn't take into account that the IDs have changed from Monday to Thursday. My bad. I will make a new dump today with correct relations.

**Comment by kbevers** [comment] 2018-12-10 12:39
Should be fixed in https://github.com/Kortforsyningen/FIRE-DDL/pull/35

**Closed by kbevers** 2018-12-10 12:39 UTC
